import React from "react";
import "./globals.css";
import Menu from "../components/menu";
import { AuthProvider } from './contexts/authContext';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Menu />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
