FROM node:22.10.0-slim

WORKDIR /app/backend/

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

COPY wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it

EXPOSE 8081

CMD ["sh", "-c", "wait-for-it db:3306 -- npm start"]
