version: '3.8'  # Assurez-vous d'utiliser une version de Docker Compose qui prend en charge les déploiements

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dragove12*
      MYSQL_DATABASE: Memoire
    ports:
      - "3306:3306"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Limite CPU à 0.5 vCPU (50% d'un vCPU)
          memory: 1G    # Limite mémoire à 1 Go

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Dragove12*
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.2'   # Limite CPU à 0.2 vCPU (20% d'un vCPU)
          memory: 512M   # Limite mémoire à 512 Mo

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: Dragove12*
      MYSQL_DATABASE: Memoire
    command: sh -c "wait-for-it db:3306 -- npm start"
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'     # Limite CPU à 1 vCPU
          memory: 2G     # Limite mémoire à 2 Go

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'     # Limite CPU à 1 vCPU
          memory: 2G     # Limite mémoire à 2 Go

networks:
  app-network:
    driver: bridge
