name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Changez cela selon le nom de votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
            cd gestion-event/AppliCalLocal/
            
            # Arrêter et supprimer uniquement les conteneurs (ne pas supprimer les volumes pour conserver les données)
            docker-compose down
            
            # Nettoyer les images non utilisées sans affecter les volumes
            docker image prune -f
            
            # Mettre à jour le code
            cd ../..
            rm -rf gestion-event/
            mkdir gestion-event
            cd gestion-event/
            git clone https://github.com/Zainados2/gestion-event.git .
            cd AppliCalLocal/
            
            # Recréer les conteneurs et mettre à jour les images si nécessaire
            docker-compose up -d --build

            docker builder prune --filter "until=24h"
