name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 5 : Installer Node.js pour le frontend
    - name: Setup Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '22.10.0'

    # Étape 6 : Installer les dépendances pour le frontend
    - name: Install Frontend Dependencies
      working-directory: AppliCalLocal/frontend
      run: npm install

    # Étape 7 : Exécuter les tests pour le frontend
    - name: Run Frontend Tests
      working-directory: AppliCalLocal/frontend/src
      run: npm test

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
            cd gestion-event/AppliCalLocal/
            
            docker-compose down
            
            cd ../..
            rm -rf gestion-event/
            mkdir gestion-event
            cd gestion-event/
            git clone https://github.com/Zainados2/gestion-event.git .
            cd AppliCalLocal/
            
            docker-compose up -d --build

            docker builder prune --filter "until=24h"
