name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Changez cela selon le nom de votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
            cd gestion-event/AppliCalLocal/
            docker-compose down
            cd ../..
            rm -rf gestion-event/
            # Créer le nouveau répertoire gestion-event
            echo "Creating new gestion-event directory..."
            mkdir gestion-event
            
            # Se placer dans le répertoire gestion-event
            cd gestion-event/
            
            # Cloner le dépôt
            echo "Cloning gestion-event..."
            git clone https://github.com/Zainados2/gestion-event.git .
            
            # Se placer dans AppliCalLocal
            cd AppliCalLocal/
            
            # Lancer les commandes Docker
            echo "Starting Docker containers..."
            docker-compose up -d --build  # Reconstruit et démarre les conteneurs en mode détaché
            
            echo 'Deployment to DigitalOcean finished'
