name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Changez cela selon le nom de votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
            # Navigation vers le répertoire de gestion-event
            cd ~/gestion-event
            
            # Clonage ou mise à jour du dépôt directement dans le répertoire gestion-event
            if [ ! -d ".git" ]; then
                echo "Cloning gestion-event..."
                git clone https://github.com/Zainados2/gestion-event.git .
            else
                echo "Updating gestion-event..."
                git pull origin main
            fi
            
            # Supprimer le dossier .github si nécessaire
            rm -rf .github  # Supprime le dossier .github

            # Lancer les commandes Docker
            cd AppliCalLocal/
            docker-compose down  # Stoppe et supprime les conteneurs existants
            docker-compose up -d --build  # Reconstruit et démarre les conteneurs en mode détaché
            echo 'Deployment to DigitalOcean finished'
